on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

name: "Build & Release"
jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.0'
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk --debug --split-per-abi
      - run: pwd && ls -l
      - run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
          pwd
          ls -l
          
      - name: Check_file & Path
        run: pwd && ls -l  
          
      - name: Check_file & Path
        run: ls -l build/ios/iphoneos && pwd
          
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
         artifacts: "build/app/outputs/apk/debug/*,build/ios/iphoneos/app.ipa"
         tag: v1.0.${{ github.run_number }}
         token: ${{ secrets.Githun_Token }}
          
          
                
        
        
        
#       - name: Distribute ipa to App Center
#         uses: akiojin/appcenter-distribute-github-action@v1
#         with:
#            app: demoapp_ios/IOS
#            token: ${{ secrets.APP_CENTER_TOKEN }}
#            #artifacts: build/ios/iphoneos/app.ipa
#            path:  build/ios/iphoneos/app.ipa 
#            group: 'tester'
#            mandatory: true
#            silent: false


      - name: Distribute ipa to App Center
        uses: akiojin/appcenter-distribute-github-action@v1
        with:
          app: kumarvineet011/Flutter
          token: ${{secrets.APP_TOKEN}}
          group: 'Tests'
          build-number: ${{ github.run_number }}
          path: build/ios/iphoneos/app.ipa
          mandatory: true
          silent: false
          release_notes: "Deployment successed"           

  
          
          
          
          
          
          
          
          
          

#       - name: App Center
#         uses: wzieba/AppCenter-Github-Action@v1.3.3
#         with:
#          appName: kumarvineet011/flutter_ios
#          token: ${{secrets.IOS_TOKEN}}
#  #        group: demoapp
#          file: /Users/runner/work/ios_flutter_sm_github_action/ios_flutter_sm_github_action/build/ios/iphoneos/app.ipa
#          notifyTesters: true
#          debug: false 
